
{
    'name': 'Employee Late Check-in',
    'version': '13.0.1.0.0',
    'summary': """This module Allows Employee Late check-in deduction/penalty""",
    'description': """This module Allows Employee Late check-in deduction/penalty""",
   'author': 'Banibro IT Solutions Pvt Ltd.',
    'company': 'Banibro IT Solutions Pvt Ltd.',
    'website': 'https://banibro.com',
    'maintainer': 'Cybrosys Techno Solutions',
    'category': 'Human Resources',
    'depends': ['hr_attendance', 'hr_payroll_community', 'hr_contract'],
    'data': [
        'views/res_config_settings.xml',
        'views/hr_attendance_view.xml',
        'views/late_check_in_view.xml',
        'views/hr_employee.xml',
        'security/ir.model.access.csv',
        'data/cron.xml',
        'data/salary_rule.xml',
    ],
    'images': ['static/description/banner.png'],
   'license': 'AGPL-3',
    'email': "support@banibro.com",
    'installable': True,
    'auto_install': False,
    'application': False,
}
